[Interface]
PrivateKey = 8Fy7eHLh78VWUTaNoTUsO5/YjcKXP7kXZ4v9BlinjE8=
Address = 10.0.0.3/24
DNS = 8.8.8.8, 1.1.1.1
MTU = 1420

[Peer]
PublicKey = 9ClTcJ/m1iYXo6CSBZhQhPFeARtKn4pr+sKF/5HXDWs=
Endpoint = hivemindvpn.justin0711.com:51820
AllowedIPs = 10.0.0.0/24
PersistentKeepalive = 25
