[package]
name = "hivemind-master-api"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tokio.workspace = true
tonic.workspace = true
axum.workspace = true
tower-http.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
tracing.workspace = true
anyhow.workspace = true
jsonwebtoken.workspace = true
hivemind-proto = { path = "../proto" }
hivemind-models = { path = "../models" }
hivemind-config = { path = "../config" }
hivemind-client-runtime = { path = "../client-runtime" }
general-compute-runtime = { path = "../../../executor-rs/crates/general-compute-runtime" }

[dev-dependencies]
tower.workspace = true
uuid.workspace = true
sqlx.workspace = true
bcrypt.workspace = true
hivemind-auth = { path = "../auth" }
hivemind-database = { path = "../database" }
hivemind-node-manager = { path = "../node-manager" }
hivemind-task-scheduler = { path = "../task-scheduler" }
