// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: hivemind.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_hivemind_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hivemind_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_hivemind_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	StatusMessage string                 `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_hivemind_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hivemind_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_hivemind_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LoginResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_hivemind_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hivemind_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_hivemind_proto_rawDescGZIP(), []int{2}
}

func (x *GetBalanceRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetBalanceRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	StatusMessage string                 `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	Balance       int64                  `protobuf:"varint,3,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_hivemind_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hivemind_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_hivemind_proto_rawDescGZIP(), []int{3}
}

func (x *GetBalanceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetBalanceResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *GetBalanceResponse) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type RegisterWorkerNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"` //用戶名
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`             //ip
	CpuCores      int32                  `protobuf:"varint,3,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemoryGb      int32                  `protobuf:"varint,4,opt,name=memory_gb,json=memoryGb,proto3" json:"memory_gb,omitempty"`
	CpuScore      int32                  `protobuf:"varint,5,opt,name=cpu_score,json=cpuScore,proto3" json:"cpu_score,omitempty"`
	GpuScore      int32                  `protobuf:"varint,6,opt,name=gpu_score,json=gpuScore,proto3" json:"gpu_score,omitempty"`
	GpuMemoryGb   int32                  `protobuf:"varint,7,opt,name=gpu_memory_gb,json=gpuMemoryGb,proto3" json:"gpu_memory_gb,omitempty"`
	Location      string                 `protobuf:"bytes,8,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkerNodeRequest) Reset() {
	*x = RegisterWorkerNodeRequest{}
	mi := &file_hivemind_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerNodeRequest) ProtoMessage() {}

func (x *RegisterWorkerNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hivemind_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterWorkerNodeRequest) Descriptor() ([]byte, []int) {
	return file_hivemind_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterWorkerNodeRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterWorkerNodeRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *RegisterWorkerNodeRequest) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *RegisterWorkerNodeRequest) GetMemoryGb() int32 {
	if x != nil {
		return x.MemoryGb
	}
	return 0
}

func (x *RegisterWorkerNodeRequest) GetCpuScore() int32 {
	if x != nil {
		return x.CpuScore
	}
	return 0
}

func (x *RegisterWorkerNodeRequest) GetGpuScore() int32 {
	if x != nil {
		return x.GpuScore
	}
	return 0
}

func (x *RegisterWorkerNodeRequest) GetGpuMemoryGb() int32 {
	if x != nil {
		return x.GpuMemoryGb
	}
	return 0
}

func (x *RegisterWorkerNodeRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	StatusMessage string                 `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_hivemind_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hivemind_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_hivemind_proto_rawDescGZIP(), []int{5}
}

func (x *StatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StatusResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

type RunningStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Username       string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`                                       // 用戶名，用於識別報告節點
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                           // 節點狀態 (Idle, Busy, Error等)
	CpuUsage       float32                `protobuf:"fixed32,3,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`                     // CPU 使用率 (百分比浮點)
	MemoryUsage    float32                `protobuf:"fixed32,4,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`            // 記憶體使用率 (百分比浮點)
	GpuUsage       float32                `protobuf:"fixed32,5,opt,name=gpu_usage,json=gpuUsage,proto3" json:"gpu_usage,omitempty"`                     // GPU 使用率 (百分比浮點)
	GpuMemoryUsage float32                `protobuf:"fixed32,6,opt,name=gpu_memory_usage,json=gpuMemoryUsage,proto3" json:"gpu_memory_usage,omitempty"` // GPU 記憶體使用率 (百分比浮點)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RunningStatusRequest) Reset() {
	*x = RunningStatusRequest{}
	mi := &file_hivemind_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunningStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunningStatusRequest) ProtoMessage() {}

func (x *RunningStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hivemind_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunningStatusRequest.ProtoReflect.Descriptor instead.
func (*RunningStatusRequest) Descriptor() ([]byte, []int) {
	return file_hivemind_proto_rawDescGZIP(), []int{6}
}

func (x *RunningStatusRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RunningStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RunningStatusRequest) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *RunningStatusRequest) GetMemoryUsage() float32 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *RunningStatusRequest) GetGpuUsage() float32 {
	if x != nil {
		return x.GpuUsage
	}
	return 0
}

func (x *RunningStatusRequest) GetGpuMemoryUsage() float32 {
	if x != nil {
		return x.GpuMemoryUsage
	}
	return 0
}

type RunningStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	StatusMessage string                 `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunningStatusResponse) Reset() {
	*x = RunningStatusResponse{}
	mi := &file_hivemind_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunningStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunningStatusResponse) ProtoMessage() {}

func (x *RunningStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hivemind_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunningStatusResponse.ProtoReflect.Descriptor instead.
func (*RunningStatusResponse) Descriptor() ([]byte, []int) {
	return file_hivemind_proto_rawDescGZIP(), []int{7}
}

func (x *RunningStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RunningStatusResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

type UploadTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Torrent       string                 `protobuf:"bytes,2,opt,name=torrent,proto3" json:"torrent,omitempty"` // .torrent metadata or magnet URL
	MemoryGb      int32                  `protobuf:"varint,3,opt,name=memory_gb,json=memoryGb,proto3" json:"memory_gb,omitempty"`
	CpuScore      int32                  `protobuf:"varint,4,opt,name=cpu_score,json=cpuScore,proto3" json:"cpu_score,omitempty"`
	GpuScore      int32                  `protobuf:"varint,5,opt,name=gpu_score,json=gpuScore,proto3" json:"gpu_score,omitempty"`
	GpuMemoryGb   int32                  `protobuf:"varint,6,opt,name=gpu_memory_gb,json=gpuMemoryGb,proto3" json:"gpu_memory_gb,omitempty"`
	Location      string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	HostCount     int32                  `protobuf:"varint,8,opt,name=host_count,json=hostCount,proto3" json:"host_count,omitempty"` // 需要的工作節點數量
	Token         string                 `protobuf:"bytes,9,opt,name=token,proto3" json:"token,omitempty"`                           // 用戶令牌，用於驗證（最後一個欄位）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadTaskRequest) Reset() {
	*x = UploadTaskRequest{}
	mi := &file_hivemind_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadTaskRequest) ProtoMessage() {}

func (x *UploadTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hivemind_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadTaskRequest.ProtoReflect.Descriptor instead.
func (*UploadTaskRequest) Descriptor() ([]byte, []int) {
	return file_hivemind_proto_rawDescGZIP(), []int{8}
}

func (x *UploadTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *UploadTaskRequest) GetTorrent() string {
	if x != nil {
		return x.Torrent
	}
	return ""
}

func (x *UploadTaskRequest) GetMemoryGb() int32 {
	if x != nil {
		return x.MemoryGb
	}
	return 0
}

func (x *UploadTaskRequest) GetCpuScore() int32 {
	if x != nil {
		return x.CpuScore
	}
	return 0
}

func (x *UploadTaskRequest) GetGpuScore() int32 {
	if x != nil {
		return x.GpuScore
	}
	return 0
}

func (x *UploadTaskRequest) GetGpuMemoryGb() int32 {
	if x != nil {
		return x.GpuMemoryGb
	}
	return 0
}

func (x *UploadTaskRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UploadTaskRequest) GetHostCount() int32 {
	if x != nil {
		return x.HostCount
	}
	return 0
}

func (x *UploadTaskRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type UploadTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	StatusMessage string                 `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadTaskResponse) Reset() {
	*x = UploadTaskResponse{}
	mi := &file_hivemind_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadTaskResponse) ProtoMessage() {}

func (x *UploadTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hivemind_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadTaskResponse.ProtoReflect.Descriptor instead.
func (*UploadTaskResponse) Descriptor() ([]byte, []int) {
	return file_hivemind_proto_rawDescGZIP(), []int{9}
}

func (x *UploadTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadTaskResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

type GetAllUserTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // 用戶令牌，用於驗證
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUserTasksRequest) Reset() {
	*x = GetAllUserTasksRequest{}
	mi := &file_hivemind_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUserTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUserTasksRequest) ProtoMessage() {}

func (x *GetAllUserTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hivemind_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUserTasksRequest.ProtoReflect.Descriptor instead.
func (*GetAllUserTasksRequest) Descriptor() ([]byte, []int) {
	return file_hivemind_proto_rawDescGZIP(), []int{10}
}

func (x *GetAllUserTasksRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetAllUserTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*TaskInfo            `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUserTasksResponse) Reset() {
	*x = GetAllUserTasksResponse{}
	mi := &file_hivemind_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUserTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUserTasksResponse) ProtoMessage() {}

func (x *GetAllUserTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hivemind_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUserTasksResponse.ProtoReflect.Descriptor instead.
func (*GetAllUserTasksResponse) Descriptor() ([]byte, []int) {
	return file_hivemind_proto_rawDescGZIP(), []int{11}
}

func (x *GetAllUserTasksResponse) GetTasks() []*TaskInfo {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type TaskInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	StatusMessage  string                 `protobuf:"bytes,3,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	CpuUsage       float32                `protobuf:"fixed32,4,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`                     // CPU 使用率 (百分比浮點)
	MemoryUsage    float32                `protobuf:"fixed32,5,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`            // 記憶體使用率 (百分比浮點)
	GpuUsage       float32                `protobuf:"fixed32,6,opt,name=gpu_usage,json=gpuUsage,proto3" json:"gpu_usage,omitempty"`                     // GPU 使用率 (百分比浮點)
	GpuMemoryUsage float32                `protobuf:"fixed32,7,opt,name=gpu_memory_usage,json=gpuMemoryUsage,proto3" json:"gpu_memory_usage,omitempty"` // GPU 記憶體使用率 (百分比浮點)
	WorkerIp       string                 `protobuf:"bytes,8,opt,name=worker_ip,json=workerIp,proto3" json:"worker_ip,omitempty"`                       // 工作節點 IP
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskInfo) Reset() {
	*x = TaskInfo{}
	mi := &file_hivemind_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInfo) ProtoMessage() {}

func (x *TaskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_hivemind_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInfo.ProtoReflect.Descriptor instead.
func (*TaskInfo) Descriptor() ([]byte, []int) {
	return file_hivemind_proto_rawDescGZIP(), []int{12}
}

func (x *TaskInfo) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskInfo) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *TaskInfo) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *TaskInfo) GetMemoryUsage() float32 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *TaskInfo) GetGpuUsage() float32 {
	if x != nil {
		return x.GpuUsage
	}
	return 0
}

func (x *TaskInfo) GetGpuMemoryUsage() float32 {
	if x != nil {
		return x.GpuMemoryUsage
	}
	return 0
}

func (x *TaskInfo) GetWorkerIp() string {
	if x != nil {
		return x.WorkerIp
	}
	return ""
}

type TaskOutputUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"` // 用戶令牌，用於驗證
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskOutputUploadRequest) Reset() {
	*x = TaskOutputUploadRequest{}
	mi := &file_hivemind_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskOutputUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskOutputUploadRequest) ProtoMessage() {}

func (x *TaskOutputUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hivemind_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskOutputUploadRequest.ProtoReflect.Descriptor instead.
func (*TaskOutputUploadRequest) Descriptor() ([]byte, []int) {
	return file_hivemind_proto_rawDescGZIP(), []int{13}
}

func (x *TaskOutputUploadRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskOutputUploadRequest) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *TaskOutputUploadRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type TaskOutputUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	StatusMessage string                 `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskOutputUploadResponse) Reset() {
	*x = TaskOutputUploadResponse{}
	mi := &file_hivemind_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskOutputUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskOutputUploadResponse) ProtoMessage() {}

func (x *TaskOutputUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hivemind_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskOutputUploadResponse.ProtoReflect.Descriptor instead.
func (*TaskOutputUploadResponse) Descriptor() ([]byte, []int) {
	return file_hivemind_proto_rawDescGZIP(), []int{14}
}

func (x *TaskOutputUploadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskOutputUploadResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

type TaskResultUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ResultTorrent string                 `protobuf:"bytes,2,opt,name=result_torrent,json=resultTorrent,proto3" json:"result_torrent,omitempty"` // .torrent metadata or magnet URL for result
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`                                      // 用戶令牌，用於驗證
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResultUploadRequest) Reset() {
	*x = TaskResultUploadRequest{}
	mi := &file_hivemind_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResultUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResultUploadRequest) ProtoMessage() {}

func (x *TaskResultUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hivemind_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResultUploadRequest.ProtoReflect.Descriptor instead.
func (*TaskResultUploadRequest) Descriptor() ([]byte, []int) {
	return file_hivemind_proto_rawDescGZIP(), []int{15}
}

func (x *TaskResultUploadRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResultUploadRequest) GetResultTorrent() string {
	if x != nil {
		return x.ResultTorrent
	}
	return ""
}

func (x *TaskResultUploadRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type TaskResultUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	StatusMessage string                 `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResultUploadResponse) Reset() {
	*x = TaskResultUploadResponse{}
	mi := &file_hivemind_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResultUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResultUploadResponse) ProtoMessage() {}

func (x *TaskResultUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hivemind_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResultUploadResponse.ProtoReflect.Descriptor instead.
func (*TaskResultUploadResponse) Descriptor() ([]byte, []int) {
	return file_hivemind_proto_rawDescGZIP(), []int{16}
}

func (x *TaskResultUploadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskResultUploadResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

type GetTaskResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"` // 用戶令牌，用於驗證
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResultRequest) Reset() {
	*x = GetTaskResultRequest{}
	mi := &file_hivemind_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResultRequest) ProtoMessage() {}

func (x *GetTaskResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hivemind_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResultRequest.ProtoReflect.Descriptor instead.
func (*GetTaskResultRequest) Descriptor() ([]byte, []int) {
	return file_hivemind_proto_rawDescGZIP(), []int{17}
}

func (x *GetTaskResultRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetTaskResultRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetTaskResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	StatusMessage string                 `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	ResultTorrent string                 `protobuf:"bytes,3,opt,name=result_torrent,json=resultTorrent,proto3" json:"result_torrent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResultResponse) Reset() {
	*x = GetTaskResultResponse{}
	mi := &file_hivemind_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResultResponse) ProtoMessage() {}

func (x *GetTaskResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hivemind_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResultResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResultResponse) Descriptor() ([]byte, []int) {
	return file_hivemind_proto_rawDescGZIP(), []int{18}
}

func (x *GetTaskResultResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetTaskResultResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *GetTaskResultResponse) GetResultTorrent() string {
	if x != nil {
		return x.ResultTorrent
	}
	return ""
}

type ExecuteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Torrent       string                 `protobuf:"bytes,2,opt,name=torrent,proto3" json:"torrent,omitempty"`                     // .torrent metadata or magnet URL
	CpuUsage      float32                `protobuf:"fixed32,3,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"` // 可選：浮點初始 CPU 配額或使用率
	GpuUsage      float32                `protobuf:"fixed32,4,opt,name=gpu_usage,json=gpuUsage,proto3" json:"gpu_usage,omitempty"` // 可選：浮點初始 GPU 配額或使用率
	MemoryGb      int32                  `protobuf:"varint,5,opt,name=memory_gb,json=memoryGb,proto3" json:"memory_gb,omitempty"`
	GpuMemoryGb   int32                  `protobuf:"varint,6,opt,name=gpu_memory_gb,json=gpuMemoryGb,proto3" json:"gpu_memory_gb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteTaskRequest) Reset() {
	*x = ExecuteTaskRequest{}
	mi := &file_hivemind_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTaskRequest) ProtoMessage() {}

func (x *ExecuteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hivemind_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTaskRequest.ProtoReflect.Descriptor instead.
func (*ExecuteTaskRequest) Descriptor() ([]byte, []int) {
	return file_hivemind_proto_rawDescGZIP(), []int{19}
}

func (x *ExecuteTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ExecuteTaskRequest) GetTorrent() string {
	if x != nil {
		return x.Torrent
	}
	return ""
}

func (x *ExecuteTaskRequest) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *ExecuteTaskRequest) GetGpuUsage() float32 {
	if x != nil {
		return x.GpuUsage
	}
	return 0
}

func (x *ExecuteTaskRequest) GetMemoryGb() int32 {
	if x != nil {
		return x.MemoryGb
	}
	return 0
}

func (x *ExecuteTaskRequest) GetGpuMemoryGb() int32 {
	if x != nil {
		return x.GpuMemoryGb
	}
	return 0
}

type ExecuteTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	StatusMessage string                 `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteTaskResponse) Reset() {
	*x = ExecuteTaskResponse{}
	mi := &file_hivemind_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTaskResponse) ProtoMessage() {}

func (x *ExecuteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hivemind_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTaskResponse.ProtoReflect.Descriptor instead.
func (*ExecuteTaskResponse) Descriptor() ([]byte, []int) {
	return file_hivemind_proto_rawDescGZIP(), []int{20}
}

func (x *ExecuteTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteTaskResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

type TaskOutputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"` // 用戶令牌，用於驗證
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskOutputRequest) Reset() {
	*x = TaskOutputRequest{}
	mi := &file_hivemind_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskOutputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskOutputRequest) ProtoMessage() {}

func (x *TaskOutputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hivemind_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskOutputRequest.ProtoReflect.Descriptor instead.
func (*TaskOutputRequest) Descriptor() ([]byte, []int) {
	return file_hivemind_proto_rawDescGZIP(), []int{21}
}

func (x *TaskOutputRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskOutputRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type TaskOutputResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	StatusMessage string                 `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	Output        string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskOutputResponse) Reset() {
	*x = TaskOutputResponse{}
	mi := &file_hivemind_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskOutputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskOutputResponse) ProtoMessage() {}

func (x *TaskOutputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hivemind_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskOutputResponse.ProtoReflect.Descriptor instead.
func (*TaskOutputResponse) Descriptor() ([]byte, []int) {
	return file_hivemind_proto_rawDescGZIP(), []int{22}
}

func (x *TaskOutputResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskOutputResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *TaskOutputResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type StopTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopTaskRequest) Reset() {
	*x = StopTaskRequest{}
	mi := &file_hivemind_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTaskRequest) ProtoMessage() {}

func (x *StopTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hivemind_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTaskRequest.ProtoReflect.Descriptor instead.
func (*StopTaskRequest) Descriptor() ([]byte, []int) {
	return file_hivemind_proto_rawDescGZIP(), []int{23}
}

func (x *StopTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *StopTaskRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type StopTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	StatusMessage string                 `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopTaskResponse) Reset() {
	*x = StopTaskResponse{}
	mi := &file_hivemind_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTaskResponse) ProtoMessage() {}

func (x *StopTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hivemind_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTaskResponse.ProtoReflect.Descriptor instead.
func (*StopTaskResponse) Descriptor() ([]byte, []int) {
	return file_hivemind_proto_rawDescGZIP(), []int{24}
}

func (x *StopTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopTaskResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

type StopTaskExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopTaskExecutionRequest) Reset() {
	*x = StopTaskExecutionRequest{}
	mi := &file_hivemind_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTaskExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTaskExecutionRequest) ProtoMessage() {}

func (x *StopTaskExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hivemind_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTaskExecutionRequest.ProtoReflect.Descriptor instead.
func (*StopTaskExecutionRequest) Descriptor() ([]byte, []int) {
	return file_hivemind_proto_rawDescGZIP(), []int{25}
}

func (x *StopTaskExecutionRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type StopTaskExecutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	StatusMessage string                 `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopTaskExecutionResponse) Reset() {
	*x = StopTaskExecutionResponse{}
	mi := &file_hivemind_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTaskExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTaskExecutionResponse) ProtoMessage() {}

func (x *StopTaskExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hivemind_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTaskExecutionResponse.ProtoReflect.Descriptor instead.
func (*StopTaskExecutionResponse) Descriptor() ([]byte, []int) {
	return file_hivemind_proto_rawDescGZIP(), []int{26}
}

func (x *StopTaskExecutionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopTaskExecutionResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

type TaskUsageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	CpuUsage       float32                `protobuf:"fixed32,2,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`                     // CPU 使用率 (百分比浮點)
	MemoryUsage    float32                `protobuf:"fixed32,3,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`            // 記憶體使用率 (百分比浮點)
	GpuUsage       float32                `protobuf:"fixed32,4,opt,name=gpu_usage,json=gpuUsage,proto3" json:"gpu_usage,omitempty"`                     // GPU 使用率 (百分比浮點)
	GpuMemoryUsage float32                `protobuf:"fixed32,5,opt,name=gpu_memory_usage,json=gpuMemoryUsage,proto3" json:"gpu_memory_usage,omitempty"` // GPU 記憶體使用率 (百分比浮點)
	Token          string                 `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`                                             // 用戶令牌，用於驗證
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskUsageRequest) Reset() {
	*x = TaskUsageRequest{}
	mi := &file_hivemind_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskUsageRequest) ProtoMessage() {}

func (x *TaskUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hivemind_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskUsageRequest.ProtoReflect.Descriptor instead.
func (*TaskUsageRequest) Descriptor() ([]byte, []int) {
	return file_hivemind_proto_rawDescGZIP(), []int{27}
}

func (x *TaskUsageRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskUsageRequest) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *TaskUsageRequest) GetMemoryUsage() float32 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *TaskUsageRequest) GetGpuUsage() float32 {
	if x != nil {
		return x.GpuUsage
	}
	return 0
}

func (x *TaskUsageRequest) GetGpuMemoryUsage() float32 {
	if x != nil {
		return x.GpuMemoryUsage
	}
	return 0
}

func (x *TaskUsageRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type TaskUsageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	StatusMessage string                 `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskUsageResponse) Reset() {
	*x = TaskUsageResponse{}
	mi := &file_hivemind_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskUsageResponse) ProtoMessage() {}

func (x *TaskUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hivemind_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskUsageResponse.ProtoReflect.Descriptor instead.
func (*TaskUsageResponse) Descriptor() ([]byte, []int) {
	return file_hivemind_proto_rawDescGZIP(), []int{28}
}

func (x *TaskUsageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskUsageResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldToken      string                 `protobuf:"bytes,1,opt,name=old_token,json=oldToken,proto3" json:"old_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_hivemind_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hivemind_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_hivemind_proto_rawDescGZIP(), []int{29}
}

func (x *RefreshTokenRequest) GetOldToken() string {
	if x != nil {
		return x.OldToken
	}
	return ""
}

type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	StatusMessage string                 `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	NewToken      string                 `protobuf:"bytes,3,opt,name=new_token,json=newToken,proto3" json:"new_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_hivemind_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hivemind_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_hivemind_proto_rawDescGZIP(), []int{30}
}

func (x *RefreshTokenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RefreshTokenResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *RefreshTokenResponse) GetNewToken() string {
	if x != nil {
		return x.NewToken
	}
	return ""
}

type TasklogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"` // 用戶令牌，用於驗證
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TasklogRequest) Reset() {
	*x = TasklogRequest{}
	mi := &file_hivemind_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TasklogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TasklogRequest) ProtoMessage() {}

func (x *TasklogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hivemind_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TasklogRequest.ProtoReflect.Descriptor instead.
func (*TasklogRequest) Descriptor() ([]byte, []int) {
	return file_hivemind_proto_rawDescGZIP(), []int{31}
}

func (x *TasklogRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TasklogRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type TasklogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Log           string                 `protobuf:"bytes,2,opt,name=log,proto3" json:"log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TasklogResponse) Reset() {
	*x = TasklogResponse{}
	mi := &file_hivemind_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TasklogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TasklogResponse) ProtoMessage() {}

func (x *TasklogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hivemind_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TasklogResponse.ProtoReflect.Descriptor instead.
func (*TasklogResponse) Descriptor() ([]byte, []int) {
	return file_hivemind_proto_rawDescGZIP(), []int{32}
}

func (x *TasklogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TasklogResponse) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

var File_hivemind_proto protoreflect.FileDescriptor

const file_hivemind_proto_rawDesc = "" +
	"\n" +
	"\x0ehivemind.proto\x12\bnodepool\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"f\n" +
	"\rLoginResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0estatus_message\x18\x02 \x01(\tR\rstatusMessage\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"E\n" +
	"\x11GetBalanceRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"o\n" +
	"\x12GetBalanceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0estatus_message\x18\x02 \x01(\tR\rstatusMessage\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x03R\abalance\"\xfb\x01\n" +
	"\x19RegisterWorkerNodeRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x1b\n" +
	"\tcpu_cores\x18\x03 \x01(\x05R\bcpuCores\x12\x1b\n" +
	"\tmemory_gb\x18\x04 \x01(\x05R\bmemoryGb\x12\x1b\n" +
	"\tcpu_score\x18\x05 \x01(\x05R\bcpuScore\x12\x1b\n" +
	"\tgpu_score\x18\x06 \x01(\x05R\bgpuScore\x12\"\n" +
	"\rgpu_memory_gb\x18\a \x01(\x05R\vgpuMemoryGb\x12\x1a\n" +
	"\blocation\x18\b \x01(\tR\blocation\"Q\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0estatus_message\x18\x02 \x01(\tR\rstatusMessage\"\xd1\x01\n" +
	"\x14RunningStatusRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1b\n" +
	"\tcpu_usage\x18\x03 \x01(\x02R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x04 \x01(\x02R\vmemoryUsage\x12\x1b\n" +
	"\tgpu_usage\x18\x05 \x01(\x02R\bgpuUsage\x12(\n" +
	"\x10gpu_memory_usage\x18\x06 \x01(\x02R\x0egpuMemoryUsage\"X\n" +
	"\x15RunningStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0estatus_message\x18\x02 \x01(\tR\rstatusMessage\"\x92\x02\n" +
	"\x11UploadTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\atorrent\x18\x02 \x01(\tR\atorrent\x12\x1b\n" +
	"\tmemory_gb\x18\x03 \x01(\x05R\bmemoryGb\x12\x1b\n" +
	"\tcpu_score\x18\x04 \x01(\x05R\bcpuScore\x12\x1b\n" +
	"\tgpu_score\x18\x05 \x01(\x05R\bgpuScore\x12\"\n" +
	"\rgpu_memory_gb\x18\x06 \x01(\x05R\vgpuMemoryGb\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\x12\x1d\n" +
	"\n" +
	"host_count\x18\b \x01(\x05R\thostCount\x12\x14\n" +
	"\x05token\x18\t \x01(\tR\x05token\"U\n" +
	"\x12UploadTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0estatus_message\x18\x02 \x01(\tR\rstatusMessage\".\n" +
	"\x16GetAllUserTasksRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"C\n" +
	"\x17GetAllUserTasksResponse\x12(\n" +
	"\x05tasks\x18\x01 \x03(\v2\x12.nodepool.TaskInfoR\x05tasks\"\x86\x02\n" +
	"\bTaskInfo\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12%\n" +
	"\x0estatus_message\x18\x03 \x01(\tR\rstatusMessage\x12\x1b\n" +
	"\tcpu_usage\x18\x04 \x01(\x02R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x05 \x01(\x02R\vmemoryUsage\x12\x1b\n" +
	"\tgpu_usage\x18\x06 \x01(\x02R\bgpuUsage\x12(\n" +
	"\x10gpu_memory_usage\x18\a \x01(\x02R\x0egpuMemoryUsage\x12\x1b\n" +
	"\tworker_ip\x18\b \x01(\tR\bworkerIp\"`\n" +
	"\x17TaskOutputUploadRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"[\n" +
	"\x18TaskOutputUploadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0estatus_message\x18\x02 \x01(\tR\rstatusMessage\"o\n" +
	"\x17TaskResultUploadRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12%\n" +
	"\x0eresult_torrent\x18\x02 \x01(\tR\rresultTorrent\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"[\n" +
	"\x18TaskResultUploadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0estatus_message\x18\x02 \x01(\tR\rstatusMessage\"E\n" +
	"\x14GetTaskResultRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"\x7f\n" +
	"\x15GetTaskResultResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0estatus_message\x18\x02 \x01(\tR\rstatusMessage\x12%\n" +
	"\x0eresult_torrent\x18\x03 \x01(\tR\rresultTorrent\"\xc2\x01\n" +
	"\x12ExecuteTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\atorrent\x18\x02 \x01(\tR\atorrent\x12\x1b\n" +
	"\tcpu_usage\x18\x03 \x01(\x02R\bcpuUsage\x12\x1b\n" +
	"\tgpu_usage\x18\x04 \x01(\x02R\bgpuUsage\x12\x1b\n" +
	"\tmemory_gb\x18\x05 \x01(\x05R\bmemoryGb\x12\"\n" +
	"\rgpu_memory_gb\x18\x06 \x01(\x05R\vgpuMemoryGb\"V\n" +
	"\x13ExecuteTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0estatus_message\x18\x02 \x01(\tR\rstatusMessage\"B\n" +
	"\x11TaskOutputRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"m\n" +
	"\x12TaskOutputResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0estatus_message\x18\x02 \x01(\tR\rstatusMessage\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\"@\n" +
	"\x0fStopTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"S\n" +
	"\x10StopTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0estatus_message\x18\x02 \x01(\tR\rstatusMessage\"3\n" +
	"\x18StopTaskExecutionRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\\\n" +
	"\x19StopTaskExecutionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0estatus_message\x18\x02 \x01(\tR\rstatusMessage\"\xc8\x01\n" +
	"\x10TaskUsageRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tcpu_usage\x18\x02 \x01(\x02R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x03 \x01(\x02R\vmemoryUsage\x12\x1b\n" +
	"\tgpu_usage\x18\x04 \x01(\x02R\bgpuUsage\x12(\n" +
	"\x10gpu_memory_usage\x18\x05 \x01(\x02R\x0egpuMemoryUsage\x12\x14\n" +
	"\x05token\x18\x06 \x01(\tR\x05token\"T\n" +
	"\x11TaskUsageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0estatus_message\x18\x02 \x01(\tR\rstatusMessage\"2\n" +
	"\x13RefreshTokenRequest\x12\x1b\n" +
	"\told_token\x18\x01 \x01(\tR\boldToken\"t\n" +
	"\x14RefreshTokenResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0estatus_message\x18\x02 \x01(\tR\rstatusMessage\x12\x1b\n" +
	"\tnew_token\x18\x03 \x01(\tR\bnewToken\"?\n" +
	"\x0eTasklogRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"=\n" +
	"\x0fTasklogResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x10\n" +
	"\x03log\x18\x02 \x01(\tR\x03log2\xdf\x01\n" +
	"\vUserService\x128\n" +
	"\x05Login\x12\x16.nodepool.LoginRequest\x1a\x17.nodepool.LoginResponse\x12G\n" +
	"\n" +
	"GetBalance\x12\x1b.nodepool.GetBalanceRequest\x1a\x1c.nodepool.GetBalanceResponse\x12M\n" +
	"\fRefreshToken\x12\x1d.nodepool.RefreshTokenRequest\x1a\x1e.nodepool.RefreshTokenResponse2\xba\x01\n" +
	"\x12NodeManagerService\x12S\n" +
	"\x12RegisterWorkerNode\x12#.nodepool.RegisterWorkerNodeRequest\x1a\x18.nodepool.StatusResponse\x12O\n" +
	"\fReportStatus\x12\x1e.nodepool.RunningStatusRequest\x1a\x1f.nodepool.RunningStatusResponse2\x8c\x03\n" +
	"\x11MasterNodeService\x12G\n" +
	"\n" +
	"UploadTask\x12\x1b.nodepool.UploadTaskRequest\x1a\x1c.nodepool.UploadTaskResponse\x12P\n" +
	"\rGetTaskResult\x12\x1e.nodepool.GetTaskResultRequest\x1a\x1f.nodepool.GetTaskResultResponse\x12V\n" +
	"\x0fGetAllUserTasks\x12 .nodepool.GetAllUserTasksRequest\x1a!.nodepool.GetAllUserTasksResponse\x12A\n" +
	"\bStopTask\x12\x19.nodepool.StopTaskRequest\x1a\x1a.nodepool.StopTaskResponse\x12A\n" +
	"\n" +
	"GetTasklog\x12\x18.nodepool.TasklogRequest\x1a\x19.nodepool.TasklogResponse2\x82\x04\n" +
	"\x11WorkerNodeService\x12J\n" +
	"\vExecuteTask\x12\x1c.nodepool.ExecuteTaskRequest\x1a\x1d.nodepool.ExecuteTaskResponse\x12Y\n" +
	"\x10TaskOutputUpload\x12!.nodepool.TaskOutputUploadRequest\x1a\".nodepool.TaskOutputUploadResponse\x12Y\n" +
	"\x10TaskResultUpload\x12!.nodepool.TaskResultUploadRequest\x1a\".nodepool.TaskResultUploadResponse\x12G\n" +
	"\n" +
	"TaskOutput\x12\x1b.nodepool.TaskOutputRequest\x1a\x1c.nodepool.TaskOutputResponse\x12\\\n" +
	"\x11StopTaskExecution\x12\".nodepool.StopTaskExecutionRequest\x1a#.nodepool.StopTaskExecutionResponse\x12D\n" +
	"\tTaskUsage\x12\x1a.nodepool.TaskUsageRequest\x1a\x1b.nodepool.TaskUsageResponseb\x06proto3"

var (
	file_hivemind_proto_rawDescOnce sync.Once
	file_hivemind_proto_rawDescData []byte
)

func file_hivemind_proto_rawDescGZIP() []byte {
	file_hivemind_proto_rawDescOnce.Do(func() {
		file_hivemind_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hivemind_proto_rawDesc), len(file_hivemind_proto_rawDesc)))
	})
	return file_hivemind_proto_rawDescData
}

var file_hivemind_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_hivemind_proto_goTypes = []any{
	(*LoginRequest)(nil),              // 0: nodepool.LoginRequest
	(*LoginResponse)(nil),             // 1: nodepool.LoginResponse
	(*GetBalanceRequest)(nil),         // 2: nodepool.GetBalanceRequest
	(*GetBalanceResponse)(nil),        // 3: nodepool.GetBalanceResponse
	(*RegisterWorkerNodeRequest)(nil), // 4: nodepool.RegisterWorkerNodeRequest
	(*StatusResponse)(nil),            // 5: nodepool.StatusResponse
	(*RunningStatusRequest)(nil),      // 6: nodepool.RunningStatusRequest
	(*RunningStatusResponse)(nil),     // 7: nodepool.RunningStatusResponse
	(*UploadTaskRequest)(nil),         // 8: nodepool.UploadTaskRequest
	(*UploadTaskResponse)(nil),        // 9: nodepool.UploadTaskResponse
	(*GetAllUserTasksRequest)(nil),    // 10: nodepool.GetAllUserTasksRequest
	(*GetAllUserTasksResponse)(nil),   // 11: nodepool.GetAllUserTasksResponse
	(*TaskInfo)(nil),                  // 12: nodepool.TaskInfo
	(*TaskOutputUploadRequest)(nil),   // 13: nodepool.TaskOutputUploadRequest
	(*TaskOutputUploadResponse)(nil),  // 14: nodepool.TaskOutputUploadResponse
	(*TaskResultUploadRequest)(nil),   // 15: nodepool.TaskResultUploadRequest
	(*TaskResultUploadResponse)(nil),  // 16: nodepool.TaskResultUploadResponse
	(*GetTaskResultRequest)(nil),      // 17: nodepool.GetTaskResultRequest
	(*GetTaskResultResponse)(nil),     // 18: nodepool.GetTaskResultResponse
	(*ExecuteTaskRequest)(nil),        // 19: nodepool.ExecuteTaskRequest
	(*ExecuteTaskResponse)(nil),       // 20: nodepool.ExecuteTaskResponse
	(*TaskOutputRequest)(nil),         // 21: nodepool.TaskOutputRequest
	(*TaskOutputResponse)(nil),        // 22: nodepool.TaskOutputResponse
	(*StopTaskRequest)(nil),           // 23: nodepool.StopTaskRequest
	(*StopTaskResponse)(nil),          // 24: nodepool.StopTaskResponse
	(*StopTaskExecutionRequest)(nil),  // 25: nodepool.StopTaskExecutionRequest
	(*StopTaskExecutionResponse)(nil), // 26: nodepool.StopTaskExecutionResponse
	(*TaskUsageRequest)(nil),          // 27: nodepool.TaskUsageRequest
	(*TaskUsageResponse)(nil),         // 28: nodepool.TaskUsageResponse
	(*RefreshTokenRequest)(nil),       // 29: nodepool.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),      // 30: nodepool.RefreshTokenResponse
	(*TasklogRequest)(nil),            // 31: nodepool.TasklogRequest
	(*TasklogResponse)(nil),           // 32: nodepool.TasklogResponse
}
var file_hivemind_proto_depIdxs = []int32{
	12, // 0: nodepool.GetAllUserTasksResponse.tasks:type_name -> nodepool.TaskInfo
	0,  // 1: nodepool.UserService.Login:input_type -> nodepool.LoginRequest
	2,  // 2: nodepool.UserService.GetBalance:input_type -> nodepool.GetBalanceRequest
	29, // 3: nodepool.UserService.RefreshToken:input_type -> nodepool.RefreshTokenRequest
	4,  // 4: nodepool.NodeManagerService.RegisterWorkerNode:input_type -> nodepool.RegisterWorkerNodeRequest
	6,  // 5: nodepool.NodeManagerService.ReportStatus:input_type -> nodepool.RunningStatusRequest
	8,  // 6: nodepool.MasterNodeService.UploadTask:input_type -> nodepool.UploadTaskRequest
	17, // 7: nodepool.MasterNodeService.GetTaskResult:input_type -> nodepool.GetTaskResultRequest
	10, // 8: nodepool.MasterNodeService.GetAllUserTasks:input_type -> nodepool.GetAllUserTasksRequest
	23, // 9: nodepool.MasterNodeService.StopTask:input_type -> nodepool.StopTaskRequest
	31, // 10: nodepool.MasterNodeService.GetTasklog:input_type -> nodepool.TasklogRequest
	19, // 11: nodepool.WorkerNodeService.ExecuteTask:input_type -> nodepool.ExecuteTaskRequest
	13, // 12: nodepool.WorkerNodeService.TaskOutputUpload:input_type -> nodepool.TaskOutputUploadRequest
	15, // 13: nodepool.WorkerNodeService.TaskResultUpload:input_type -> nodepool.TaskResultUploadRequest
	21, // 14: nodepool.WorkerNodeService.TaskOutput:input_type -> nodepool.TaskOutputRequest
	25, // 15: nodepool.WorkerNodeService.StopTaskExecution:input_type -> nodepool.StopTaskExecutionRequest
	27, // 16: nodepool.WorkerNodeService.TaskUsage:input_type -> nodepool.TaskUsageRequest
	1,  // 17: nodepool.UserService.Login:output_type -> nodepool.LoginResponse
	3,  // 18: nodepool.UserService.GetBalance:output_type -> nodepool.GetBalanceResponse
	30, // 19: nodepool.UserService.RefreshToken:output_type -> nodepool.RefreshTokenResponse
	5,  // 20: nodepool.NodeManagerService.RegisterWorkerNode:output_type -> nodepool.StatusResponse
	7,  // 21: nodepool.NodeManagerService.ReportStatus:output_type -> nodepool.RunningStatusResponse
	9,  // 22: nodepool.MasterNodeService.UploadTask:output_type -> nodepool.UploadTaskResponse
	18, // 23: nodepool.MasterNodeService.GetTaskResult:output_type -> nodepool.GetTaskResultResponse
	11, // 24: nodepool.MasterNodeService.GetAllUserTasks:output_type -> nodepool.GetAllUserTasksResponse
	24, // 25: nodepool.MasterNodeService.StopTask:output_type -> nodepool.StopTaskResponse
	32, // 26: nodepool.MasterNodeService.GetTasklog:output_type -> nodepool.TasklogResponse
	20, // 27: nodepool.WorkerNodeService.ExecuteTask:output_type -> nodepool.ExecuteTaskResponse
	14, // 28: nodepool.WorkerNodeService.TaskOutputUpload:output_type -> nodepool.TaskOutputUploadResponse
	16, // 29: nodepool.WorkerNodeService.TaskResultUpload:output_type -> nodepool.TaskResultUploadResponse
	22, // 30: nodepool.WorkerNodeService.TaskOutput:output_type -> nodepool.TaskOutputResponse
	26, // 31: nodepool.WorkerNodeService.StopTaskExecution:output_type -> nodepool.StopTaskExecutionResponse
	28, // 32: nodepool.WorkerNodeService.TaskUsage:output_type -> nodepool.TaskUsageResponse
	17, // [17:33] is the sub-list for method output_type
	1,  // [1:17] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_hivemind_proto_init() }
func file_hivemind_proto_init() {
	if File_hivemind_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hivemind_proto_rawDesc), len(file_hivemind_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_hivemind_proto_goTypes,
		DependencyIndexes: file_hivemind_proto_depIdxs,
		MessageInfos:      file_hivemind_proto_msgTypes,
	}.Build()
	File_hivemind_proto = out.File
	file_hivemind_proto_goTypes = nil
	file_hivemind_proto_depIdxs = nil
}
