// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.5
// source: hivemind.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BatchRuntimeService_PullBatch_FullMethodName     = "/nodepool.BatchRuntimeService/PullBatch"
	BatchRuntimeService_CompleteBatch_FullMethodName = "/nodepool.BatchRuntimeService/CompleteBatch"
	BatchRuntimeService_Heartbeat_FullMethodName     = "/nodepool.BatchRuntimeService/Heartbeat"
)

// BatchRuntimeServiceClient is the client API for BatchRuntimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BatchRuntimeServiceClient interface {
	PullBatch(ctx context.Context, in *PullBatchRequest, opts ...grpc.CallOption) (*PullBatchResponse, error)
	CompleteBatch(ctx context.Context, in *CompleteBatchRequest, opts ...grpc.CallOption) (*CompleteBatchResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
}

type batchRuntimeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBatchRuntimeServiceClient(cc grpc.ClientConnInterface) BatchRuntimeServiceClient {
	return &batchRuntimeServiceClient{cc}
}

func (c *batchRuntimeServiceClient) PullBatch(ctx context.Context, in *PullBatchRequest, opts ...grpc.CallOption) (*PullBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PullBatchResponse)
	err := c.cc.Invoke(ctx, BatchRuntimeService_PullBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *batchRuntimeServiceClient) CompleteBatch(ctx context.Context, in *CompleteBatchRequest, opts ...grpc.CallOption) (*CompleteBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteBatchResponse)
	err := c.cc.Invoke(ctx, BatchRuntimeService_CompleteBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *batchRuntimeServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, BatchRuntimeService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BatchRuntimeServiceServer is the server API for BatchRuntimeService service.
// All implementations must embed UnimplementedBatchRuntimeServiceServer
// for forward compatibility.
type BatchRuntimeServiceServer interface {
	PullBatch(context.Context, *PullBatchRequest) (*PullBatchResponse, error)
	CompleteBatch(context.Context, *CompleteBatchRequest) (*CompleteBatchResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	mustEmbedUnimplementedBatchRuntimeServiceServer()
}

// UnimplementedBatchRuntimeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBatchRuntimeServiceServer struct{}

func (UnimplementedBatchRuntimeServiceServer) PullBatch(context.Context, *PullBatchRequest) (*PullBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PullBatch not implemented")
}
func (UnimplementedBatchRuntimeServiceServer) CompleteBatch(context.Context, *CompleteBatchRequest) (*CompleteBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteBatch not implemented")
}
func (UnimplementedBatchRuntimeServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedBatchRuntimeServiceServer) mustEmbedUnimplementedBatchRuntimeServiceServer() {}
func (UnimplementedBatchRuntimeServiceServer) testEmbeddedByValue()                             {}

// UnsafeBatchRuntimeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BatchRuntimeServiceServer will
// result in compilation errors.
type UnsafeBatchRuntimeServiceServer interface {
	mustEmbedUnimplementedBatchRuntimeServiceServer()
}

func RegisterBatchRuntimeServiceServer(s grpc.ServiceRegistrar, srv BatchRuntimeServiceServer) {
	// If the following call panics, it indicates UnimplementedBatchRuntimeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BatchRuntimeService_ServiceDesc, srv)
}

func _BatchRuntimeService_PullBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BatchRuntimeServiceServer).PullBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BatchRuntimeService_PullBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BatchRuntimeServiceServer).PullBatch(ctx, req.(*PullBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BatchRuntimeService_CompleteBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BatchRuntimeServiceServer).CompleteBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BatchRuntimeService_CompleteBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BatchRuntimeServiceServer).CompleteBatch(ctx, req.(*CompleteBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BatchRuntimeService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BatchRuntimeServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BatchRuntimeService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BatchRuntimeServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BatchRuntimeService_ServiceDesc is the grpc.ServiceDesc for BatchRuntimeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BatchRuntimeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nodepool.BatchRuntimeService",
	HandlerType: (*BatchRuntimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PullBatch",
			Handler:    _BatchRuntimeService_PullBatch_Handler,
		},
		{
			MethodName: "CompleteBatch",
			Handler:    _BatchRuntimeService_CompleteBatch_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _BatchRuntimeService_Heartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hivemind.proto",
}

const (
	UserService_Login_FullMethodName        = "/nodepool.UserService/Login"
	UserService_GetBalance_FullMethodName   = "/nodepool.UserService/GetBalance"
	UserService_RefreshToken_FullMethodName = "/nodepool.UserService/RefreshToken"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error)
	RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, UserService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBalanceResponse)
	err := c.cc.Invoke(ctx, UserService_GetBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshTokenResponse)
	err := c.cc.Invoke(ctx, UserService_RefreshToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility.
type UserServiceServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error)
	RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedUserServiceServer) GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedUserServiceServer) RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshToken not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}
func (UnimplementedUserServiceServer) testEmbeddedByValue()                     {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	// If the following call panics, it indicates UnimplementedUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetBalance(ctx, req.(*GetBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_RefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RefreshToken(ctx, req.(*RefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nodepool.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _UserService_Login_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _UserService_GetBalance_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _UserService_RefreshToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hivemind.proto",
}

const (
	NodeManagerService_RegisterWorkerNode_FullMethodName = "/nodepool.NodeManagerService/RegisterWorkerNode"
	NodeManagerService_ReportStatus_FullMethodName       = "/nodepool.NodeManagerService/ReportStatus"
)

// NodeManagerServiceClient is the client API for NodeManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeManagerServiceClient interface {
	RegisterWorkerNode(ctx context.Context, in *RegisterWorkerNodeRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	ReportStatus(ctx context.Context, in *RunningStatusRequest, opts ...grpc.CallOption) (*RunningStatusResponse, error)
}

type nodeManagerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeManagerServiceClient(cc grpc.ClientConnInterface) NodeManagerServiceClient {
	return &nodeManagerServiceClient{cc}
}

func (c *nodeManagerServiceClient) RegisterWorkerNode(ctx context.Context, in *RegisterWorkerNodeRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, NodeManagerService_RegisterWorkerNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeManagerServiceClient) ReportStatus(ctx context.Context, in *RunningStatusRequest, opts ...grpc.CallOption) (*RunningStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunningStatusResponse)
	err := c.cc.Invoke(ctx, NodeManagerService_ReportStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeManagerServiceServer is the server API for NodeManagerService service.
// All implementations must embed UnimplementedNodeManagerServiceServer
// for forward compatibility.
type NodeManagerServiceServer interface {
	RegisterWorkerNode(context.Context, *RegisterWorkerNodeRequest) (*StatusResponse, error)
	ReportStatus(context.Context, *RunningStatusRequest) (*RunningStatusResponse, error)
	mustEmbedUnimplementedNodeManagerServiceServer()
}

// UnimplementedNodeManagerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeManagerServiceServer struct{}

func (UnimplementedNodeManagerServiceServer) RegisterWorkerNode(context.Context, *RegisterWorkerNodeRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterWorkerNode not implemented")
}
func (UnimplementedNodeManagerServiceServer) ReportStatus(context.Context, *RunningStatusRequest) (*RunningStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportStatus not implemented")
}
func (UnimplementedNodeManagerServiceServer) mustEmbedUnimplementedNodeManagerServiceServer() {}
func (UnimplementedNodeManagerServiceServer) testEmbeddedByValue()                            {}

// UnsafeNodeManagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeManagerServiceServer will
// result in compilation errors.
type UnsafeNodeManagerServiceServer interface {
	mustEmbedUnimplementedNodeManagerServiceServer()
}

func RegisterNodeManagerServiceServer(s grpc.ServiceRegistrar, srv NodeManagerServiceServer) {
	// If the following call panics, it indicates UnimplementedNodeManagerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeManagerService_ServiceDesc, srv)
}

func _NodeManagerService_RegisterWorkerNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterWorkerNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeManagerServiceServer).RegisterWorkerNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeManagerService_RegisterWorkerNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeManagerServiceServer).RegisterWorkerNode(ctx, req.(*RegisterWorkerNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeManagerService_ReportStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunningStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeManagerServiceServer).ReportStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeManagerService_ReportStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeManagerServiceServer).ReportStatus(ctx, req.(*RunningStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeManagerService_ServiceDesc is the grpc.ServiceDesc for NodeManagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeManagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nodepool.NodeManagerService",
	HandlerType: (*NodeManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterWorkerNode",
			Handler:    _NodeManagerService_RegisterWorkerNode_Handler,
		},
		{
			MethodName: "ReportStatus",
			Handler:    _NodeManagerService_ReportStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hivemind.proto",
}

const (
	MasterNodeService_UploadTask_FullMethodName      = "/nodepool.MasterNodeService/UploadTask"
	MasterNodeService_GetTaskResult_FullMethodName   = "/nodepool.MasterNodeService/GetTaskResult"
	MasterNodeService_GetAllUserTasks_FullMethodName = "/nodepool.MasterNodeService/GetAllUserTasks"
	MasterNodeService_StopTask_FullMethodName        = "/nodepool.MasterNodeService/StopTask"
	MasterNodeService_GetTasklog_FullMethodName      = "/nodepool.MasterNodeService/GetTasklog"
)

// MasterNodeServiceClient is the client API for MasterNodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MasterNodeServiceClient interface {
	UploadTask(ctx context.Context, in *UploadTaskRequest, opts ...grpc.CallOption) (*UploadTaskResponse, error)
	GetTaskResult(ctx context.Context, in *GetTaskResultRequest, opts ...grpc.CallOption) (*GetTaskResultResponse, error)
	GetAllUserTasks(ctx context.Context, in *GetAllUserTasksRequest, opts ...grpc.CallOption) (*GetAllUserTasksResponse, error)
	StopTask(ctx context.Context, in *StopTaskRequest, opts ...grpc.CallOption) (*StopTaskResponse, error)
	GetTasklog(ctx context.Context, in *TasklogRequest, opts ...grpc.CallOption) (*TasklogResponse, error)
}

type masterNodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMasterNodeServiceClient(cc grpc.ClientConnInterface) MasterNodeServiceClient {
	return &masterNodeServiceClient{cc}
}

func (c *masterNodeServiceClient) UploadTask(ctx context.Context, in *UploadTaskRequest, opts ...grpc.CallOption) (*UploadTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadTaskResponse)
	err := c.cc.Invoke(ctx, MasterNodeService_UploadTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterNodeServiceClient) GetTaskResult(ctx context.Context, in *GetTaskResultRequest, opts ...grpc.CallOption) (*GetTaskResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskResultResponse)
	err := c.cc.Invoke(ctx, MasterNodeService_GetTaskResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterNodeServiceClient) GetAllUserTasks(ctx context.Context, in *GetAllUserTasksRequest, opts ...grpc.CallOption) (*GetAllUserTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllUserTasksResponse)
	err := c.cc.Invoke(ctx, MasterNodeService_GetAllUserTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterNodeServiceClient) StopTask(ctx context.Context, in *StopTaskRequest, opts ...grpc.CallOption) (*StopTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopTaskResponse)
	err := c.cc.Invoke(ctx, MasterNodeService_StopTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterNodeServiceClient) GetTasklog(ctx context.Context, in *TasklogRequest, opts ...grpc.CallOption) (*TasklogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TasklogResponse)
	err := c.cc.Invoke(ctx, MasterNodeService_GetTasklog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MasterNodeServiceServer is the server API for MasterNodeService service.
// All implementations must embed UnimplementedMasterNodeServiceServer
// for forward compatibility.
type MasterNodeServiceServer interface {
	UploadTask(context.Context, *UploadTaskRequest) (*UploadTaskResponse, error)
	GetTaskResult(context.Context, *GetTaskResultRequest) (*GetTaskResultResponse, error)
	GetAllUserTasks(context.Context, *GetAllUserTasksRequest) (*GetAllUserTasksResponse, error)
	StopTask(context.Context, *StopTaskRequest) (*StopTaskResponse, error)
	GetTasklog(context.Context, *TasklogRequest) (*TasklogResponse, error)
	mustEmbedUnimplementedMasterNodeServiceServer()
}

// UnimplementedMasterNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMasterNodeServiceServer struct{}

func (UnimplementedMasterNodeServiceServer) UploadTask(context.Context, *UploadTaskRequest) (*UploadTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadTask not implemented")
}
func (UnimplementedMasterNodeServiceServer) GetTaskResult(context.Context, *GetTaskResultRequest) (*GetTaskResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaskResult not implemented")
}
func (UnimplementedMasterNodeServiceServer) GetAllUserTasks(context.Context, *GetAllUserTasksRequest) (*GetAllUserTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllUserTasks not implemented")
}
func (UnimplementedMasterNodeServiceServer) StopTask(context.Context, *StopTaskRequest) (*StopTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopTask not implemented")
}
func (UnimplementedMasterNodeServiceServer) GetTasklog(context.Context, *TasklogRequest) (*TasklogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTasklog not implemented")
}
func (UnimplementedMasterNodeServiceServer) mustEmbedUnimplementedMasterNodeServiceServer() {}
func (UnimplementedMasterNodeServiceServer) testEmbeddedByValue()                           {}

// UnsafeMasterNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MasterNodeServiceServer will
// result in compilation errors.
type UnsafeMasterNodeServiceServer interface {
	mustEmbedUnimplementedMasterNodeServiceServer()
}

func RegisterMasterNodeServiceServer(s grpc.ServiceRegistrar, srv MasterNodeServiceServer) {
	// If the following call panics, it indicates UnimplementedMasterNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MasterNodeService_ServiceDesc, srv)
}

func _MasterNodeService_UploadTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterNodeServiceServer).UploadTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterNodeService_UploadTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterNodeServiceServer).UploadTask(ctx, req.(*UploadTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterNodeService_GetTaskResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterNodeServiceServer).GetTaskResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterNodeService_GetTaskResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterNodeServiceServer).GetTaskResult(ctx, req.(*GetTaskResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterNodeService_GetAllUserTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllUserTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterNodeServiceServer).GetAllUserTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterNodeService_GetAllUserTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterNodeServiceServer).GetAllUserTasks(ctx, req.(*GetAllUserTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterNodeService_StopTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterNodeServiceServer).StopTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterNodeService_StopTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterNodeServiceServer).StopTask(ctx, req.(*StopTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterNodeService_GetTasklog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TasklogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterNodeServiceServer).GetTasklog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterNodeService_GetTasklog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterNodeServiceServer).GetTasklog(ctx, req.(*TasklogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MasterNodeService_ServiceDesc is the grpc.ServiceDesc for MasterNodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MasterNodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nodepool.MasterNodeService",
	HandlerType: (*MasterNodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadTask",
			Handler:    _MasterNodeService_UploadTask_Handler,
		},
		{
			MethodName: "GetTaskResult",
			Handler:    _MasterNodeService_GetTaskResult_Handler,
		},
		{
			MethodName: "GetAllUserTasks",
			Handler:    _MasterNodeService_GetAllUserTasks_Handler,
		},
		{
			MethodName: "StopTask",
			Handler:    _MasterNodeService_StopTask_Handler,
		},
		{
			MethodName: "GetTasklog",
			Handler:    _MasterNodeService_GetTasklog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hivemind.proto",
}

const (
	WorkerNodeService_ExecuteTask_FullMethodName       = "/nodepool.WorkerNodeService/ExecuteTask"
	WorkerNodeService_TaskOutputUpload_FullMethodName  = "/nodepool.WorkerNodeService/TaskOutputUpload"
	WorkerNodeService_TaskResultUpload_FullMethodName  = "/nodepool.WorkerNodeService/TaskResultUpload"
	WorkerNodeService_TaskOutput_FullMethodName        = "/nodepool.WorkerNodeService/TaskOutput"
	WorkerNodeService_StopTaskExecution_FullMethodName = "/nodepool.WorkerNodeService/StopTaskExecution"
	WorkerNodeService_TaskUsage_FullMethodName         = "/nodepool.WorkerNodeService/TaskUsage"
)

// WorkerNodeServiceClient is the client API for WorkerNodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkerNodeServiceClient interface {
	ExecuteTask(ctx context.Context, in *ExecuteTaskRequest, opts ...grpc.CallOption) (*ExecuteTaskResponse, error)
	TaskOutputUpload(ctx context.Context, in *TaskOutputUploadRequest, opts ...grpc.CallOption) (*TaskOutputUploadResponse, error)
	TaskResultUpload(ctx context.Context, in *TaskResultUploadRequest, opts ...grpc.CallOption) (*TaskResultUploadResponse, error)
	TaskOutput(ctx context.Context, in *TaskOutputRequest, opts ...grpc.CallOption) (*TaskOutputResponse, error)
	StopTaskExecution(ctx context.Context, in *StopTaskExecutionRequest, opts ...grpc.CallOption) (*StopTaskExecutionResponse, error)
	TaskUsage(ctx context.Context, in *TaskUsageRequest, opts ...grpc.CallOption) (*TaskUsageResponse, error)
}

type workerNodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerNodeServiceClient(cc grpc.ClientConnInterface) WorkerNodeServiceClient {
	return &workerNodeServiceClient{cc}
}

func (c *workerNodeServiceClient) ExecuteTask(ctx context.Context, in *ExecuteTaskRequest, opts ...grpc.CallOption) (*ExecuteTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteTaskResponse)
	err := c.cc.Invoke(ctx, WorkerNodeService_ExecuteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerNodeServiceClient) TaskOutputUpload(ctx context.Context, in *TaskOutputUploadRequest, opts ...grpc.CallOption) (*TaskOutputUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskOutputUploadResponse)
	err := c.cc.Invoke(ctx, WorkerNodeService_TaskOutputUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerNodeServiceClient) TaskResultUpload(ctx context.Context, in *TaskResultUploadRequest, opts ...grpc.CallOption) (*TaskResultUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResultUploadResponse)
	err := c.cc.Invoke(ctx, WorkerNodeService_TaskResultUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerNodeServiceClient) TaskOutput(ctx context.Context, in *TaskOutputRequest, opts ...grpc.CallOption) (*TaskOutputResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskOutputResponse)
	err := c.cc.Invoke(ctx, WorkerNodeService_TaskOutput_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerNodeServiceClient) StopTaskExecution(ctx context.Context, in *StopTaskExecutionRequest, opts ...grpc.CallOption) (*StopTaskExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopTaskExecutionResponse)
	err := c.cc.Invoke(ctx, WorkerNodeService_StopTaskExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerNodeServiceClient) TaskUsage(ctx context.Context, in *TaskUsageRequest, opts ...grpc.CallOption) (*TaskUsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskUsageResponse)
	err := c.cc.Invoke(ctx, WorkerNodeService_TaskUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerNodeServiceServer is the server API for WorkerNodeService service.
// All implementations must embed UnimplementedWorkerNodeServiceServer
// for forward compatibility.
type WorkerNodeServiceServer interface {
	ExecuteTask(context.Context, *ExecuteTaskRequest) (*ExecuteTaskResponse, error)
	TaskOutputUpload(context.Context, *TaskOutputUploadRequest) (*TaskOutputUploadResponse, error)
	TaskResultUpload(context.Context, *TaskResultUploadRequest) (*TaskResultUploadResponse, error)
	TaskOutput(context.Context, *TaskOutputRequest) (*TaskOutputResponse, error)
	StopTaskExecution(context.Context, *StopTaskExecutionRequest) (*StopTaskExecutionResponse, error)
	TaskUsage(context.Context, *TaskUsageRequest) (*TaskUsageResponse, error)
	mustEmbedUnimplementedWorkerNodeServiceServer()
}

// UnimplementedWorkerNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerNodeServiceServer struct{}

func (UnimplementedWorkerNodeServiceServer) ExecuteTask(context.Context, *ExecuteTaskRequest) (*ExecuteTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteTask not implemented")
}
func (UnimplementedWorkerNodeServiceServer) TaskOutputUpload(context.Context, *TaskOutputUploadRequest) (*TaskOutputUploadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TaskOutputUpload not implemented")
}
func (UnimplementedWorkerNodeServiceServer) TaskResultUpload(context.Context, *TaskResultUploadRequest) (*TaskResultUploadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TaskResultUpload not implemented")
}
func (UnimplementedWorkerNodeServiceServer) TaskOutput(context.Context, *TaskOutputRequest) (*TaskOutputResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TaskOutput not implemented")
}
func (UnimplementedWorkerNodeServiceServer) StopTaskExecution(context.Context, *StopTaskExecutionRequest) (*StopTaskExecutionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopTaskExecution not implemented")
}
func (UnimplementedWorkerNodeServiceServer) TaskUsage(context.Context, *TaskUsageRequest) (*TaskUsageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TaskUsage not implemented")
}
func (UnimplementedWorkerNodeServiceServer) mustEmbedUnimplementedWorkerNodeServiceServer() {}
func (UnimplementedWorkerNodeServiceServer) testEmbeddedByValue()                           {}

// UnsafeWorkerNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerNodeServiceServer will
// result in compilation errors.
type UnsafeWorkerNodeServiceServer interface {
	mustEmbedUnimplementedWorkerNodeServiceServer()
}

func RegisterWorkerNodeServiceServer(s grpc.ServiceRegistrar, srv WorkerNodeServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkerNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkerNodeService_ServiceDesc, srv)
}

func _WorkerNodeService_ExecuteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerNodeServiceServer).ExecuteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerNodeService_ExecuteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerNodeServiceServer).ExecuteTask(ctx, req.(*ExecuteTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerNodeService_TaskOutputUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskOutputUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerNodeServiceServer).TaskOutputUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerNodeService_TaskOutputUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerNodeServiceServer).TaskOutputUpload(ctx, req.(*TaskOutputUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerNodeService_TaskResultUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskResultUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerNodeServiceServer).TaskResultUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerNodeService_TaskResultUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerNodeServiceServer).TaskResultUpload(ctx, req.(*TaskResultUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerNodeService_TaskOutput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskOutputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerNodeServiceServer).TaskOutput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerNodeService_TaskOutput_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerNodeServiceServer).TaskOutput(ctx, req.(*TaskOutputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerNodeService_StopTaskExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopTaskExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerNodeServiceServer).StopTaskExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerNodeService_StopTaskExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerNodeServiceServer).StopTaskExecution(ctx, req.(*StopTaskExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerNodeService_TaskUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerNodeServiceServer).TaskUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerNodeService_TaskUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerNodeServiceServer).TaskUsage(ctx, req.(*TaskUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkerNodeService_ServiceDesc is the grpc.ServiceDesc for WorkerNodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerNodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nodepool.WorkerNodeService",
	HandlerType: (*WorkerNodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteTask",
			Handler:    _WorkerNodeService_ExecuteTask_Handler,
		},
		{
			MethodName: "TaskOutputUpload",
			Handler:    _WorkerNodeService_TaskOutputUpload_Handler,
		},
		{
			MethodName: "TaskResultUpload",
			Handler:    _WorkerNodeService_TaskResultUpload_Handler,
		},
		{
			MethodName: "TaskOutput",
			Handler:    _WorkerNodeService_TaskOutput_Handler,
		},
		{
			MethodName: "StopTaskExecution",
			Handler:    _WorkerNodeService_StopTaskExecution_Handler,
		},
		{
			MethodName: "TaskUsage",
			Handler:    _WorkerNodeService_TaskUsage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hivemind.proto",
}
