[package]
name = "hivemind-managed-proof-guest"
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace]

[dependencies]
hivemind-managed-proof = { path = "../../../../hivemind-rs/crates/managed-proof" }
managed-function-runtime = { path = "../../../../executor-rs/crates/managed-function-runtime" }
risc0-zkvm = { version = "=3.0.6", default-features = false, features = ["std"] }
