// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nodepool.proto
// Protobuf Java Version: 4.31.1

package nodepool;

@com.google.protobuf.Generated
public interface GetNodeListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nodepool.GetNodeListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>repeated .nodepool.WorkerNodeInfo nodes = 3;</code>
   */
  java.util.List<nodepool.WorkerNodeInfo> 
      getNodesList();
  /**
   * <code>repeated .nodepool.WorkerNodeInfo nodes = 3;</code>
   */
  nodepool.WorkerNodeInfo getNodes(int index);
  /**
   * <code>repeated .nodepool.WorkerNodeInfo nodes = 3;</code>
   */
  int getNodesCount();
  /**
   * <code>repeated .nodepool.WorkerNodeInfo nodes = 3;</code>
   */
  java.util.List<? extends nodepool.WorkerNodeInfoOrBuilder> 
      getNodesOrBuilderList();
  /**
   * <code>repeated .nodepool.WorkerNodeInfo nodes = 3;</code>
   */
  nodepool.WorkerNodeInfoOrBuilder getNodesOrBuilder(
      int index);
}
