// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nodepool.proto
// Protobuf Java Version: 4.31.1

package nodepool;

@com.google.protobuf.Generated
public interface GetTaskLogsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nodepool.GetTaskLogsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   * JSON 格式的日誌數據
   * </pre>
   *
   * <code>string logs = 3;</code>
   * @return The logs.
   */
  java.lang.String getLogs();
  /**
   * <pre>
   * JSON 格式的日誌數據
   * </pre>
   *
   * <code>string logs = 3;</code>
   * @return The bytes for logs.
   */
  com.google.protobuf.ByteString
      getLogsBytes();
}
