// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nodepool.proto
// Protobuf Java Version: 4.31.1

package nodepool;

@com.google.protobuf.Generated
public interface RegisterWorkerNodeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nodepool.RegisterWorkerNodeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string node_id = 1;</code>
   * @return The nodeId.
   */
  java.lang.String getNodeId();
  /**
   * <code>string node_id = 1;</code>
   * @return The bytes for nodeId.
   */
  com.google.protobuf.ByteString
      getNodeIdBytes();

  /**
   * <code>string hostname = 2;</code>
   * @return The hostname.
   */
  java.lang.String getHostname();
  /**
   * <code>string hostname = 2;</code>
   * @return The bytes for hostname.
   */
  com.google.protobuf.ByteString
      getHostnameBytes();

  /**
   * <code>int32 cpu_cores = 3;</code>
   * @return The cpuCores.
   */
  int getCpuCores();

  /**
   * <code>int32 memory_gb = 4;</code>
   * @return The memoryGb.
   */
  int getMemoryGb();

  /**
   * <code>int32 cpu_score = 5;</code>
   * @return The cpuScore.
   */
  int getCpuScore();

  /**
   * <code>int32 gpu_score = 6;</code>
   * @return The gpuScore.
   */
  int getGpuScore();

  /**
   * <code>int32 gpu_memory_gb = 7;</code>
   * @return The gpuMemoryGb.
   */
  int getGpuMemoryGb();

  /**
   * <code>string location = 8;</code>
   * @return The location.
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 8;</code>
   * @return The bytes for location.
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>int32 port = 9;</code>
   * @return The port.
   */
  int getPort();

  /**
   * <code>string gpu_name = 12;</code>
   * @return The gpuName.
   */
  java.lang.String getGpuName();
  /**
   * <code>string gpu_name = 12;</code>
   * @return The bytes for gpuName.
   */
  com.google.protobuf.ByteString
      getGpuNameBytes();
}
