// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nodepool.proto
// Protobuf Java Version: 4.31.1

package nodepool;

@com.google.protobuf.Generated
public interface ReportStatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nodepool.ReportStatusRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string node_id = 1;</code>
   * @return The nodeId.
   */
  java.lang.String getNodeId();
  /**
   * <code>string node_id = 1;</code>
   * @return The bytes for nodeId.
   */
  com.google.protobuf.ByteString
      getNodeIdBytes();

  /**
   * <code>string status_message = 2;</code>
   * @return The statusMessage.
   */
  java.lang.String getStatusMessage();
  /**
   * <code>string status_message = 2;</code>
   * @return The bytes for statusMessage.
   */
  com.google.protobuf.ByteString
      getStatusMessageBytes();
}
