// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nodepool.proto
// Protobuf Java Version: 4.31.1

package nodepool;

@com.google.protobuf.Generated
public interface StoreOutputRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nodepool.StoreOutputRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string task_id = 1;</code>
   * @return The taskId.
   */
  java.lang.String getTaskId();
  /**
   * <code>string task_id = 1;</code>
   * @return The bytes for taskId.
   */
  com.google.protobuf.ByteString
      getTaskIdBytes();

  /**
   * <code>string output = 2;</code>
   * @return The output.
   */
  java.lang.String getOutput();
  /**
   * <code>string output = 2;</code>
   * @return The bytes for output.
   */
  com.google.protobuf.ByteString
      getOutputBytes();
}
