// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nodepool.proto
// Protobuf Java Version: 4.31.1

package nodepool;

@com.google.protobuf.Generated
public interface StoreLogsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nodepool.StoreLogsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string node_id = 1;</code>
   * @return The nodeId.
   */
  java.lang.String getNodeId();
  /**
   * <code>string node_id = 1;</code>
   * @return The bytes for nodeId.
   */
  com.google.protobuf.ByteString
      getNodeIdBytes();

  /**
   * <code>string task_id = 2;</code>
   * @return The taskId.
   */
  java.lang.String getTaskId();
  /**
   * <code>string task_id = 2;</code>
   * @return The bytes for taskId.
   */
  com.google.protobuf.ByteString
      getTaskIdBytes();

  /**
   * <pre>
   * JSON 格式的日誌數據
   * </pre>
   *
   * <code>string logs = 3;</code>
   * @return The logs.
   */
  java.lang.String getLogs();
  /**
   * <pre>
   * JSON 格式的日誌數據
   * </pre>
   *
   * <code>string logs = 3;</code>
   * @return The bytes for logs.
   */
  com.google.protobuf.ByteString
      getLogsBytes();

  /**
   * <code>int64 timestamp = 4;</code>
   * @return The timestamp.
   */
  long getTimestamp();
}
