// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nodepool.proto
// Protobuf Java Version: 4.31.1

package nodepool;

@com.google.protobuf.Generated
public interface TransferRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nodepool.TransferRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string token = 1;</code>
   * @return The token.
   */
  java.lang.String getToken();
  /**
   * <code>string token = 1;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>string receiver_username = 2;</code>
   * @return The receiverUsername.
   */
  java.lang.String getReceiverUsername();
  /**
   * <code>string receiver_username = 2;</code>
   * @return The bytes for receiverUsername.
   */
  com.google.protobuf.ByteString
      getReceiverUsernameBytes();

  /**
   * <code>int64 amount = 3;</code>
   * @return The amount.
   */
  long getAmount();
}
