// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nodepool.proto
// Protobuf Java Version: 4.31.1

package nodepool;

@com.google.protobuf.Generated
public interface UploadTaskRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nodepool.UploadTaskRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string task_id = 1;</code>
   * @return The taskId.
   */
  java.lang.String getTaskId();
  /**
   * <code>string task_id = 1;</code>
   * @return The bytes for taskId.
   */
  com.google.protobuf.ByteString
      getTaskIdBytes();

  /**
   * <code>bytes task_zip = 2;</code>
   * @return The taskZip.
   */
  com.google.protobuf.ByteString getTaskZip();

  /**
   * <code>int32 memory_gb = 3;</code>
   * @return The memoryGb.
   */
  int getMemoryGb();

  /**
   * <code>int32 cpu_score = 4;</code>
   * @return The cpuScore.
   */
  int getCpuScore();

  /**
   * <code>int32 gpu_score = 5;</code>
   * @return The gpuScore.
   */
  int getGpuScore();

  /**
   * <code>int32 gpu_memory_gb = 6;</code>
   * @return The gpuMemoryGb.
   */
  int getGpuMemoryGb();

  /**
   * <code>string location = 7;</code>
   * @return The location.
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 7;</code>
   * @return The bytes for location.
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>string gpu_name = 8;</code>
   * @return The gpuName.
   */
  java.lang.String getGpuName();
  /**
   * <code>string gpu_name = 8;</code>
   * @return The bytes for gpuName.
   */
  com.google.protobuf.ByteString
      getGpuNameBytes();

  /**
   * <pre>
   * 添加用戶ID字段
   * </pre>
   *
   * <code>string user_id = 9;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <pre>
   * 添加用戶ID字段
   * </pre>
   *
   * <code>string user_id = 9;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();
}
